[package]
name = "thrace"
version = "0.1.0"
edition = "2021"
description = "egui matrix client"
license = "AGPL-3.0-only"

[[bin]]
name = "thrace"
path = "src/main.rs"

[dependencies]
eframe = { version = "0.35", features = ["default"] }
egui = "0.35"
tokio = { version = "1", features = ["full"] }
tokio-sync = "0.1"
futures-core = "0.3"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
matrix-sdk = { version = "0.18", features = ["sqlite", "e2e-encryption", "sso-login"] }
url = "2"
rfd = "0.15"
mime = "0.3"
mime_guess = "2"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "gif", "webp"] }
parking_lot = "0.12"
pulldown-cmark = "0.12"
lru = "0.12"
reqwest = { version = "0.13", features = ["json", "rustls"], default-features = false }
ttf-parser = "0.25"
rustybuzz = "0.20"
tiny-skia = "0.11"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
arboard = { version = "3.6", features = ["image-data", "wayland-data-control"] }
secret-service = { version = "5.2.0", features = ["rt-tokio-crypto-rust"] }

[profile.release]
opt-level = 2
