/*
SPDX-License-Identifier: AGPL-3.0-only
Please see LICENSE in the repository root for full details.
*/

//! Categorized unicode emoji dataset for the picker (content only).
//!
//! `supports_skin` marks bases that accept a Fitzpatrick modifier
//! (hands, people, body parts). Applied on insert via `SKIN_TONES`.

/// One picker category: name, tab icon, and emoji bases.
///
/// `icon` keeps the tab bar narrow: a picture per category, not a word.
#[derive(Debug, Clone, Copy)]
pub struct EmojiCategory {
    pub name: &'static str,
    pub icon: &'static str,
    pub emojis: &'static [(&'static str, bool)],
}

pub const CATEGORIES: &[EmojiCategory] = &[
    EmojiCategory {
        name: "Smileys",
        icon: "\u{1F600}",
        emojis: SMILEYS,
    },
    EmojiCategory {
        name: "People",
        icon: "\u{1F44B}",
        emojis: PEOPLE,
    },
    EmojiCategory {
        name: "Animals",
        icon: "\u{1F415}",
        emojis: ANIMALS,
    },
    EmojiCategory {
        name: "Food",
        icon: "\u{1F34E}",
        emojis: FOOD,
    },
    EmojiCategory {
        name: "Activities",
        icon: "\u{26BD}",
        emojis: ACTIVITIES,
    },
    EmojiCategory {
        name: "Travel",
        icon: "\u{1F697}",
        emojis: TRAVEL,
    },
    EmojiCategory {
        name: "Objects",
        icon: "\u{1F4A1}",
        emojis: OBJECTS,
    },
    EmojiCategory {
        name: "Symbols",
        icon: "\u{2049}",
        emojis: SYMBOLS,
    },
];

pub const SMILEYS: &[(&str, bool)] = &[
    ("😀", false),
    ("😁", false),
    ("😂", false),
    ("🤣", false),
    ("😃", false),
    ("😄", false),
    ("😅", false),
    ("😆", false),
    ("😉", false),
    ("😊", false),
    ("😋", false),
    ("😎", false),
    ("😍", false),
    ("😘", false),
    ("🥰", false),
    ("😗", false),
    ("😙", false),
    ("😚", false),
    ("🙂", false),
    ("🤗", false),
    ("🤩", false),
    ("🤔", false),
    ("🤨", false),
    ("😐", false),
    ("🙄", false),
    ("😏", false),
    ("😣", false),
    ("😥", false),
    ("😮", false),
    ("🤐", false),
    ("😯", false),
    ("😪", false),
    ("😫", false),
    ("🥱", false),
    ("😴", false),
    ("😌", false),
    ("😛", false),
    ("😜", false),
    ("😝", false),
    ("🤤", false),
    ("😒", false),
    ("😓", false),
    ("😔", false),
    ("😕", false),
    ("🙃", false),
    ("🫠", false),
    ("😲", false),
    ("☹️", false),
    ("🙁", false),
    ("😖", false),
    ("😞", false),
    ("😟", false),
    ("😤", false),
    ("😢", false),
    ("😭", false),
    ("😦", false),
    ("😧", false),
    ("😨", false),
    ("😩", false),
    ("🤯", false),
    ("😬", false),
    ("😰", false),
    ("😱", false),
    ("🥵", false),
    ("🥶", false),
    ("😳", false),
    ("🤪", false),
    ("😵", false),
    ("😡", false),
    ("😠", false),
    ("🤬", false),
    ("😷", false),
    ("🤒", false),
    ("🤕", false),
    ("🤢", false),
    ("🤮", false),
    ("🤧", false),
    ("😇", false),
    ("🥳", false),
    ("🥸", false),
    ("🤠", false),
    ("🤡", false),
    ("👻", false),
    ("💀", false),
    ("☠️", false),
    ("👽", false),
    ("🤖", false),
    ("🎃", false),
    ("😺", false),
    ("😸", false),
    ("😹", false),
    ("😻", false),
    ("😼", false),
    ("😽", false),
    ("🙀", false),
    ("😿", false),
    ("😾", false),
    ("❤️", false),
    ("🧡", false),
    ("💛", false),
    ("💚", false),
    ("💙", false),
    ("💜", false),
    ("🖤", false),
    ("🤍", false),
    ("💔", false),
    ("❣️", false),
    ("💕", false),
    ("💞", false),
    ("💓", false),
    ("💗", false),
    ("💖", false),
    ("💘", false),
    ("💝", false),
    ("💟", false),
];

pub const PEOPLE: &[(&str, bool)] = &[
    ("👋", true),
    ("🤚", true),
    ("🖐️", true),
    ("✋", true),
    ("🖖", true),
    ("👌", true),
    ("🤌", true),
    ("🤏", true),
    ("✌️", true),
    ("🤞", true),
    ("🫰", true),
    ("🤟", true),
    ("🤘", true),
    ("🤙", true),
    ("👈", true),
    ("👉", true),
    ("👆", true),
    ("🖕", true),
    ("👇", true),
    ("☝️", true),
    ("👍", true),
    ("👎", true),
    ("✊", true),
    ("👊", true),
    ("🤛", true),
    ("🤜", true),
    ("👏", true),
    ("🙌", true),
    ("🫶", true),
    ("👐", true),
    ("🤲", true),
    ("🤝", true),
    ("🙏", true),
    ("✍️", true),
    ("💅", true),
    ("🤳", true),
    ("💪", true),
    ("🦾", false),
    ("🦿", true),
    ("🦵", true),
    ("🦶", true),
    ("👂", true),
    ("🦻", true),
    ("👃", true),
    ("🧠", false),
    ("🫀", false),
    ("🫁", false),
    ("🦷", false),
    ("🦴", false),
    ("👀", false),
    ("👁️", false),
    ("👅", false),
    ("👄", false),
    ("🫦", false),
    ("👶", true),
    ("🧒", true),
    ("👦", true),
    ("👧", true),
    ("🧑", true),
    ("👱", true),
    ("👨", true),
    ("🧔", true),
    ("👩", true),
    ("🧓", true),
    ("👴", true),
    ("👵", true),
    ("🙍", true),
    ("🙎", true),
    ("🙅", true),
    ("🙆", true),
    ("💁", true),
    ("🙋", true),
    ("🧏", true),
    ("🙇", true),
    ("🤦", true),
    ("🤷", true),
    ("🧑‍⚕️", true),
    ("🧑‍🎓", true),
    ("🧑‍🏫", true),
    ("🧑‍⚖️", true),
    ("🧑‍🌾", true),
    ("🧑‍🍳", true),
    ("🧑‍🔧", true),
    ("🧑‍🏭", true),
    ("🧑‍💼", true),
    ("🧑‍🔬", true),
    ("🧑‍💻", true),
    ("🧑‍🎤", true),
    ("🧑‍🎨", true),
    ("🧑‍✈️", true),
    ("🧑‍🚀", true),
    ("🧑‍🚒", true),
    ("💃", true),
    ("🕺", true),
    ("🕴️", true),
    ("🚶", true),
    ("🧍", true),
    ("🧎", true),
    ("🏃", true),
    ("🧖", true),
    ("🧗", true),
    ("🏇", true),
    ("🏂", true),
    ("🏌️", true),
    ("🏄", true),
];

pub const ANIMALS: &[(&str, bool)] = &[
    ("🐶", false),
    ("🐱", false),
    ("🐭", false),
    ("🐹", false),
    ("🐰", false),
    ("🦊", false),
    ("🐻", false),
    ("🐼", false),
    ("🐨", false),
    ("🐯", false),
    ("🦁", false),
    ("🐮", false),
    ("🐷", false),
    ("🐽", false),
    ("🐸", false),
    ("🐵", false),
    ("🙈", false),
    ("🙉", false),
    ("🙊", false),
    ("🐒", false),
    ("🐔", false),
    ("🐧", false),
    ("🐦", false),
    ("🐤", false),
    ("🦆", false),
    ("🦅", false),
    ("🦉", false),
    ("🦇", false),
    ("🐺", false),
    ("🐗", false),
    ("🐴", false),
    ("🦄", false),
    ("🐝", false),
    ("🪲", false),
    ("🦋", false),
    ("🐌", false),
    ("🐞", false),
    ("🐜", false),
    ("🪳", false),
    ("🦟", false),
    ("🦗", false),
    ("🕷️", false),
    ("🦂", false),
    ("🐢", false),
    ("🐍", false),
    ("🦎", false),
    ("🦖", false),
    ("🦕", false),
    ("🐙", false),
    ("🦑", false),
    ("🦐", false),
    ("🦞", false),
    ("🦀", false),
    ("🐡", false),
    ("🐠", false),
    ("🐟", false),
    ("🐬", false),
    ("🐳", false),
    ("🐋", false),
    ("🦈", false),
    ("🐊", false),
    ("🐅", false),
    ("🐆", false),
    ("🦓", false),
    ("🦍", false),
    ("🦧", false),
    ("🐘", false),
    ("🦛", false),
    ("🦏", false),
    ("🐪", false),
    ("🐫", false),
    ("🦒", false),
    ("🦘", false),
    ("🐃", false),
    ("🐂", false),
    ("🐄", false),
    ("🐎", false),
    ("🐖", false),
    ("🐏", false),
    ("🐑", false),
    ("🦙", false),
    ("🐐", false),
    ("🦌", false),
    ("🐕", false),
    ("🐩", false),
    ("🦮", false),
    ("🐈", false),
    ("🪶", false),
    ("🐓", false),
    ("🦃", false),
    ("🦤", false),
    ("🦚", false),
    ("🦜", false),
    ("🦢", false),
    ("🪿", false),
    ("🐇", false),
    ("🦝", false),
    ("🦨", false),
    ("🦡", false),
    ("🦦", false),
    ("🦥", false),
    ("🐁", false),
    ("🐀", false),
    ("🐿️", false),
    ("🦔", false),
    ("🌵", false),
    ("🎄", false),
    ("🌲", false),
    ("🌳", false),
    ("🌴", false),
    ("🪵", false),
    ("🌱", false),
    ("🌿", false),
    ("☘️", false),
    ("🍀", false),
    ("🎍", false),
    ("🎋", false),
    ("🍃", false),
    ("🍂", false),
    ("🍁", false),
    ("🍄", false),
    ("🌾", false),
    ("💐", false),
    ("🌷", false),
    ("🌹", false),
    ("🥀", false),
    ("🌺", false),
    ("🌸", false),
    ("🌼", false),
    ("🌻", false),
    ("🌞", false),
    ("🌝", false),
    ("🌛", false),
    ("🌜", false),
    ("🌚", false),
    ("🌕", false),
    ("🌖", false),
    ("🌗", false),
    ("🌘", false),
    ("🌑", false),
    ("🌒", false),
    ("🌓", false),
    ("🌔", false),
    ("🌙", false),
    ("🌎", false),
    ("🌍", false),
    ("🌏", false),
    ("🪐", false),
    ("💫", false),
    ("⭐", false),
    ("🌟", false),
    ("✨", false),
    ("⚡", false),
    ("☄️", false),
    ("💥", false),
    ("🔥", false),
    ("🌪️", false),
    ("🌈", false),
    ("☀️", false),
    ("🌤️", false),
    ("⛅", false),
    ("☁️", false),
    ("🌦️", false),
    ("🌧️", false),
    ("⛈️", false),
    ("🌩️", false),
    ("🌨️", false),
    ("❄️", false),
    ("☃️", false),
    ("⛄", false),
    ("🌬️", false),
    ("💨", false),
    ("💧", false),
    ("💦", false),
    ("☔", false),
    ("☂️", false),
    ("🌊", false),
    ("🌫️", false),
];

pub const FOOD: &[(&str, bool)] = &[
    ("🍏", false),
    ("🍎", false),
    ("🍐", false),
    ("🍊", false),
    ("🍋", false),
    ("🍌", false),
    ("🍉", false),
    ("🍇", false),
    ("🍓", false),
    ("🫐", false),
    ("🍈", false),
    ("🍒", false),
    ("🍑", false),
    ("🥭", false),
    ("🍍", false),
    ("🥥", false),
    ("🥝", false),
    ("🍅", false),
    ("🍆", false),
    ("🥑", false),
    ("🥦", false),
    ("🥬", false),
    ("🥒", false),
    ("🌶️", false),
    ("🫑", false),
    ("🌽", false),
    ("🥕", false),
    ("🫒", false),
    ("🧄", false),
    ("🧅", false),
    ("🥔", false),
    ("🍠", false),
    ("🫚", false),
    ("🥐", false),
    ("🥯", false),
    ("🍞", false),
    ("🥖", false),
    ("🥨", false),
    ("🧀", false),
    ("🥚", false),
    ("🍳", false),
    ("🧈", false),
    ("🥞", false),
    ("🧇", false),
    ("🥓", false),
    ("🥩", false),
    ("🍗", false),
    ("🍖", false),
    ("🦴", false),
    ("🌭", false),
    ("🍔", false),
    ("🍟", false),
    ("🍕", false),
    ("🫓", false),
    ("🥪", false),
    ("🥙", false),
    ("🧆", false),
    ("🌮", false),
    ("🌯", false),
    ("🫔", false),
    ("🥗", false),
    ("🥘", false),
    ("🫕", false),
    ("🥫", false),
    ("🍝", false),
    ("🍜", false),
    ("🍲", false),
    ("🍛", false),
    ("🍣", false),
    ("🍱", false),
    ("🥟", false),
    ("🦪", false),
    ("🍤", false),
    ("🍙", false),
    ("🍚", false),
    ("🍘", false),
    ("🍥", false),
    ("🥠", false),
    ("🥮", false),
    ("🍢", false),
    ("🍡", false),
    ("🍧", false),
    ("🍨", false),
    ("🍦", false),
    ("🥧", false),
    ("🧁", false),
    ("🍰", false),
    ("🎂", false),
    ("🍮", false),
    ("🍭", false),
    ("🍬", false),
    ("🍫", false),
    ("🍿", false),
    ("🍩", false),
    ("🍪", false),
    ("🌰", false),
    ("🥜", false),
    ("🫘", false),
    ("🍯", false),
    ("🥛", false),
    ("🫗", false),
    ("☕", false),
    ("🫖", false),
    ("🍵", false),
    ("🧃", false),
    ("🥤", false),
    ("🧋", false),
    ("🍶", false),
    ("🍺", false),
    ("🍻", false),
    ("🥂", false),
    ("🍷", false),
    ("🥃", false),
    ("🍸", false),
    ("🍹", false),
    ("🧉", false),
    ("🍾", false),
    ("🧊", false),
    ("🥄", false),
    ("🍴", false),
    ("🍽️", false),
    ("🥣", false),
    ("🥡", false),
    ("🥢", false),
    ("🧂", false),
];

pub const ACTIVITIES: &[(&str, bool)] = &[
    ("⚽", false),
    ("🏀", false),
    ("🏈", false),
    ("⚾", false),
    ("🥎", false),
    ("🎾", false),
    ("🏐", false),
    ("🏉", false),
    ("🥏", false),
    ("🎱", false),
    ("🪀", false),
    ("🏓", false),
    ("🏸", false),
    ("🏒", false),
    ("🏑", false),
    ("🥍", false),
    ("🏏", false),
    ("🪃", false),
    ("🥅", false),
    ("⛳", false),
    ("🪁", false),
    ("🏹", false),
    ("🎣", false),
    ("🤿", false),
    ("🥊", false),
    ("🥋", false),
    ("🎽", false),
    ("🛹", false),
    ("🛼", false),
    ("🛷", false),
    ("⛸️", false),
    ("🥌", false),
    ("🎿", false),
    ("⛷️", false),
    ("🏂", false),
    ("🪂", false),
    ("🏋️", true),
    ("🤼", true),
    ("🤸", true),
    ("⛹️", true),
    ("🤺", true),
    ("🏇", true),
    ("🧘", true),
    ("🏆", false),
    ("🥇", false),
    ("🥈", false),
    ("🥉", false),
    ("🏅", false),
    ("🎖️", false),
    ("🏵️", false),
    ("🎗️", false),
    ("🎫", false),
    ("🎟️", false),
    ("🎪", false),
    ("🤹", true),
    ("🎭", false),
    ("🩰", false),
    ("🎨", false),
    ("🎬", false),
    ("🎤", false),
    ("🎧", false),
    ("🎼", false),
    ("🎹", false),
    ("🥁", false),
    ("🪘", false),
    ("🎷", false),
    ("🎺", false),
    ("🪗", false),
    ("🎸", false),
    ("🪕", false),
    ("🎻", false),
    ("🎲", false),
    ("♟️", false),
    ("🎯", false),
    ("🎳", false),
    ("🎮", false),
    ("🎰", false),
    ("🧩", false),
];

pub const TRAVEL: &[(&str, bool)] = &[
    ("🚗", false),
    ("🚕", false),
    ("🚙", false),
    ("🚌", false),
    ("🚎", false),
    ("🏎️", false),
    ("🚓", false),
    ("🚑", false),
    ("🚒", false),
    ("🛻", false),
    ("🚚", false),
    ("🚛", false),
    ("🚜", false),
    ("🦯", false),
    ("🦽", false),
    ("🦼", false),
    ("🛴", false),
    ("🚲", false),
    ("🛵", false),
    ("🏍️", false),
    ("🛺", false),
    ("🚨", false),
    ("🚔", false),
    ("🚍", false),
    ("🚘", false),
    ("🚖", false),
    ("🚡", false),
    ("🚠", false),
    ("🚟", false),
    ("🚃", false),
    ("🚋", false),
    ("🚞", false),
    ("🚝", false),
    ("🚄", false),
    ("🚅", false),
    ("🚈", false),
    ("🚂", false),
    ("🚆", false),
    ("🚇", false),
    ("🚊", false),
    ("🚉", false),
    ("✈️", false),
    ("🛫", false),
    ("🛬", false),
    ("🛩️", false),
    ("💺", false),
    ("🚁", false),
    ("🚟", false),
    ("🚠", false),
    ("🚀", false),
    ("🛸", false),
    ("🚉", false),
    ("⛵", false),
    ("🛶", false),
    ("🚤", false),
    ("🛥️", false),
    ("🛳️", false),
    ("⛴️", false),
    ("🚢", false),
    ("⚓", false),
    ("🪝", false),
    ("⛽", false),
    ("🚧", false),
    ("🚦", false),
    ("🚥", false),
    ("🚏", false),
    ("🗺️", false),
    ("🗿", false),
    ("🗽", false),
    ("🗼", false),
    ("🏰", false),
    ("🏯", false),
    ("🏟️", false),
    ("🎡", false),
    ("🎢", false),
    ("🎠", false),
    ("⛲", false),
    ("⛱️", false),
    ("🏖️", false),
    ("🏝️", false),
    ("🏜️", false),
    ("🌋", false),
    ("⛰️", false),
    ("🏔️", false),
    ("🗻", false),
    ("🏕️", false),
    ("⛺", false),
    ("🏠", false),
    ("🏡", false),
    ("🏘️", false),
    ("🏚️", false),
    ("🏗️", false),
    ("🏭", false),
    ("🏢", false),
    ("🏬", false),
    ("🏣", false),
    ("🏤", false),
    ("🏥", false),
    ("🏦", false),
    ("🏨", false),
    ("🏪", false),
    ("🏫", false),
    ("🏩", false),
    ("💒", false),
    ("🏛️", false),
    ("⛪", false),
    ("🕌", false),
    ("🛕", false),
    ("🕍", false),
    ("⛩️", false),
    ("🕋", false),
    ("⛽", false),
];

pub const OBJECTS: &[(&str, bool)] = &[
    ("⌚", false),
    ("📱", false),
    ("📲", false),
    ("💻", false),
    ("⌨️", false),
    ("🖥️", false),
    ("🖨️", false),
    ("🖱️", false),
    ("🖲️", false),
    ("🕹️", false),
    ("🗜️", false),
    ("💽", false),
    ("💾", false),
    ("💿", false),
    ("📀", false),
    ("📼", false),
    ("📷", false),
    ("📸", false),
    ("📹", false),
    ("🎥", false),
    ("📽️", false),
    ("🎞️", false),
    ("📞", false),
    ("☎️", false),
    ("📟", false),
    ("📠", false),
    ("📺", false),
    ("📻", false),
    ("🎙️", false),
    ("🎚️", false),
    ("🎛️", false),
    ("🧭", false),
    ("⏱️", false),
    ("⏲️", false),
    ("⏰", false),
    ("🕰️", false),
    ("⌛", false),
    ("⏳", false),
    ("📡", false),
    ("🔋", false),
    ("🪫", false),
    ("🔌", false),
    ("💡", false),
    ("🔦", false),
    ("🕯️", false),
    ("🪔", false),
    ("🧯", false),
    ("🛢️", false),
    ("💸", false),
    ("💵", false),
    ("💴", false),
    ("💶", false),
    ("💷", false),
    ("🪙", false),
    ("💰", false),
    ("💳", false),
    ("💎", false),
    ("⚖️", false),
    ("🪜", false),
    ("🧰", false),
    ("🪛", false),
    ("🔧", false),
    ("🔨", false),
    ("⚒️", false),
    ("🛠️", false),
    ("⛏️", false),
    ("🪚", false),
    ("🔩", false),
    ("⚙️", false),
    ("🪤", false),
    ("🧱", false),
    ("⛓️", false),
    ("🧲", false),
    ("🔫", false),
    ("💣", false),
    ("🧨", false),
    ("🪓", false),
    ("🔪", false),
    ("🗡️", false),
    ("⚔️", false),
    ("🛡️", false),
    ("🚬", false),
    ("⚰️", false),
    ("🪦", false),
    ("⚱️", false),
    ("🏺", false),
    ("🔮", false),
    ("📿", false),
    ("🧿", false),
    ("💈", false),
    ("⚗️", false),
    ("🔭", false),
    ("🔬", false),
    ("🕳️", false),
    ("💊", false),
    ("💉", false),
    ("🩸", false),
    ("🧬", false),
    ("🦠", false),
    ("🧫", false),
    ("🧪", false),
    ("🌡️", false),
    ("🧹", false),
    ("🪠", false),
    ("🧺", false),
    ("🧻", false),
    ("🚽", false),
    ("🚰", false),
    ("🚿", false),
    ("🛁", false),
    ("🛀", true),
    ("🧼", false),
    ("🪥", false),
    ("🪒", false),
    ("🧽", false),
    ("🪣", false),
    ("🧷", false),
    ("🩹", false),
    ("🩼", false),
    ("🩺", false),
    ("🩻", false),
    ("🚪", false),
    ("🛗", false),
    ("🪞", false),
    ("🪟", false),
    ("🛏️", false),
    ("🛋️", false),
    ("🪑", false),
    ("🚽", false),
    ("🚿", false),
    ("🪆", false),
    ("🧸", false),
    ("🪅", false),
    ("🪩", false),
    ("🎎", false),
    ("🏮", false),
    ("🎐", false),
    ("🧧", false),
    ("✉️", false),
    ("📩", false),
    ("📨", false),
    ("📧", false),
    ("💌", false),
    ("📥", false),
    ("📤", false),
    ("📦", false),
    ("🏷️", false),
    ("🪧", false),
    ("📪", false),
    ("📫", false),
    ("📬", false),
    ("📭", false),
    ("📮", false),
    ("📯", false),
    ("📜", false),
    ("📃", false),
    ("📄", false),
    ("📑", false),
    ("🧾", false),
    ("📊", false),
    ("📈", false),
    ("📰", false),
    ("🗞️", false),
    ("📓", false),
    ("📔", false),
    ("📒", false),
    ("📕", false),
    ("📗", false),
    ("📘", false),
    ("📙", false),
    ("📚", false),
    ("📖", false),
    ("🔖", false),
    ("🧷", false),
    ("🔗", false),
    ("📎", false),
    ("🖇️", false),
    ("📐", false),
    ("📏", false),
    ("🧮", false),
    ("📌", false),
    ("📍", false),
    ("✂️", false),
    ("🖊️", false),
    ("🖋️", false),
    ("✒️", false),
    ("🖌️", false),
    ("🖍️", false),
    ("📝", false),
    ("✏️", false),
    ("🔍", false),
    ("🔎", false),
    ("🔏", false),
    ("🔐", false),
    ("🔒", false),
    ("🔓", false),
];

pub const SYMBOLS: &[(&str, bool)] = &[
    ("❤️", false),
    ("🧡", false),
    ("💛", false),
    ("💚", false),
    ("💙", false),
    ("💜", false),
    ("🖤", false),
    ("🤍", false),
    ("🤎", false),
    ("💔", false),
    ("❣️", false),
    ("💕", false),
    ("💞", false),
    ("💓", false),
    ("💗", false),
    ("💖", false),
    ("💘", false),
    ("💝", false),
    ("💟", false),
    ("☮️", false),
    ("✝️", false),
    ("☪️", false),
    ("🕉️", false),
    ("☸️", false),
    ("✡️", false),
    ("🔯", false),
    ("🕎", false),
    ("☯️", false),
    ("☦️", false),
    ("🛐", false),
    ("⛎", false),
    ("♈", false),
    ("♉", false),
    ("♊", false),
    ("♋", false),
    ("♌", false),
    ("♍", false),
    ("♎", false),
    ("♏", false),
    ("♐", false),
    ("♑", false),
    ("♒", false),
    ("♓", false),
    ("🆔", false),
    ("⚛️", false),
    ("✅", false),
    ("☑️", false),
    ("✔️", false),
    ("❌", false),
    ("❎", false),
    ("➕", false),
    ("➖", false),
    ("➗", false),
    ("✖️", false),
    ("🟰", false),
    ("➰", false),
    ("➿", false),
    ("〰️", false),
    ("✳️", false),
    ("✴️", false),
    ("❇️", false),
    ("‼️", false),
    ("⁉️", false),
    ("❓", false),
    ("❔", false),
    ("❕", false),
    ("❗", false),
    ("⭕", false),
    ("🚫", false),
    ("🚳", false),
    ("🚭", false),
    ("🚯", false),
    ("🚱", false),
    ("🚷", false),
    ("📵", false),
    ("🔞", false),
    ("☢️", false),
    ("☣️", false),
    ("⬆️", false),
    ("↗️", false),
    ("➡️", false),
    ("↘️", false),
    ("⬇️", false),
    ("↙️", false),
    ("⬅️", false),
    ("↖️", false),
    ("↕️", false),
    ("↔️", false),
    ("↩️", false),
    ("↪️", false),
    ("⤴️", false),
    ("⤵️", false),
    ("🔃", false),
    ("🔄", false),
    ("🔙", false),
    ("🔚", false),
    ("🔛", false),
    ("🔜", false),
    ("🔝", false),
    ("🛜", false),
    ("⚛️", false),
    ("🕉️", false),
    ("✡️", false),
    ("☸️", false),
    ("☯️", false),
    ("✝️", false),
    ("☦️", false),
    ("☪️", false),
    ("☮️", false),
    ("🕎", false),
    ("🔠", false),
    ("🔡", false),
    ("🔢", false),
    ("🔣", false),
    ("🔤", false),
    ("ℹ️", false),
    ("🆔", false),
    ("Ⓜ️", false),
    ("🆕", false),
    ("🆖", false),
    ("🅾️", false),
    ("🆗", false),
    ("🅿️", false),
    ("🆘", false),
    ("🆙", false),
    ("🆚", false),
    ("🈁", false),
    ("🈂️", false),
    ("🈷️", false),
    ("🈶", false),
    ("🈯", false),
    ("🉐", false),
    ("🈹", false),
    ("🈚", false),
    ("🈲", false),
    ("🉑", false),
    ("🈸", false),
    ("🈴", false),
    ("🈳", false),
    ("㊗️", false),
    ("㊙️", false),
    ("🈺", false),
    ("🈵", false),
    ("🔴", false),
    ("🟠", false),
    ("🟡", false),
    ("🟢", false),
    ("🔵", false),
    ("🟣", false),
    ("🟤", false),
    ("⚫", false),
    ("⚪", false),
    ("🟥", false),
    ("🟧", false),
    ("🟨", false),
    ("🟩", false),
    ("🟦", false),
    ("🟪", false),
    ("🟫", false),
    ("⬛", false),
    ("⬜", false),
    ("◼️", false),
    ("◻️", false),
    ("◾", false),
    ("◽", false),
    ("▪️", false),
    ("▫️", false),
    ("🔶", false),
    ("🔷", false),
    ("🔸", false),
    ("🔹", false),
    ("🔺", false),
    ("🔻", false),
    ("💠", false),
    ("🔘", false),
    ("🔳", false),
    ("🔲", false),
    ("🏁", false),
    ("🚩", false),
    ("🎌", false),
    ("🏴", false),
    ("🏳️", false),
];

/// Unicode names for every emoji in [`CATEGORIES`], for search.
///
/// Generated from Python's `unicodedata`. Sorted by glyph for binary search.
pub const NAMES: &[(&str, &str)] = &[
    ("\u{203C}\u{FE0F}", "double exclamation mark"),
    ("\u{2049}\u{FE0F}", "exclamation question mark"),
    ("\u{2139}\u{FE0F}", "information source"),
    ("\u{2194}\u{FE0F}", "left right arrow"),
    ("\u{2195}\u{FE0F}", "up down arrow"),
    ("\u{2196}\u{FE0F}", "north west arrow"),
    ("\u{2197}\u{FE0F}", "north east arrow"),
    ("\u{2198}\u{FE0F}", "south east arrow"),
    ("\u{2199}\u{FE0F}", "south west arrow"),
    ("\u{21A9}\u{FE0F}", "leftwards arrow with hook"),
    ("\u{21AA}\u{FE0F}", "rightwards arrow with hook"),
    ("\u{231A}", "watch"),
    ("\u{231B}", "hourglass"),
    ("\u{2328}\u{FE0F}", "keyboard"),
    ("\u{23F0}", "alarm clock"),
    ("\u{23F1}\u{FE0F}", "stopwatch"),
    ("\u{23F2}\u{FE0F}", "timer clock"),
    ("\u{23F3}", "hourglass with flowing sand"),
    ("\u{24C2}\u{FE0F}", "circled latin capital letter m"),
    ("\u{25AA}\u{FE0F}", "black small square"),
    ("\u{25AB}\u{FE0F}", "white small square"),
    ("\u{25FB}\u{FE0F}", "white medium square"),
    ("\u{25FC}\u{FE0F}", "black medium square"),
    ("\u{25FD}", "white medium small square"),
    ("\u{25FE}", "black medium small square"),
    ("\u{2600}\u{FE0F}", "black sun with rays"),
    ("\u{2601}\u{FE0F}", "cloud"),
    ("\u{2602}\u{FE0F}", "umbrella"),
    ("\u{2603}\u{FE0F}", "snowman"),
    ("\u{2604}\u{FE0F}", "comet"),
    ("\u{260E}\u{FE0F}", "black telephone"),
    ("\u{2611}\u{FE0F}", "ballot box with check"),
    ("\u{2614}", "umbrella with rain drops"),
    ("\u{2615}", "hot beverage"),
    ("\u{2618}\u{FE0F}", "shamrock"),
    ("\u{261D}\u{FE0F}", "white up pointing index"),
    ("\u{2620}\u{FE0F}", "skull and crossbones"),
    ("\u{2622}\u{FE0F}", "radioactive sign"),
    ("\u{2623}\u{FE0F}", "biohazard sign"),
    ("\u{2626}\u{FE0F}", "orthodox cross"),
    ("\u{262A}\u{FE0F}", "star and crescent"),
    ("\u{262E}\u{FE0F}", "peace symbol"),
    ("\u{262F}\u{FE0F}", "yin yang"),
    ("\u{2638}\u{FE0F}", "wheel of dharma"),
    ("\u{2639}\u{FE0F}", "white frowning face"),
    ("\u{2648}", "aries"),
    ("\u{2649}", "taurus"),
    ("\u{264A}", "gemini"),
    ("\u{264B}", "cancer"),
    ("\u{264C}", "leo"),
    ("\u{264D}", "virgo"),
    ("\u{264E}", "libra"),
    ("\u{264F}", "scorpius"),
    ("\u{2650}", "sagittarius"),
    ("\u{2651}", "capricorn"),
    ("\u{2652}", "aquarius"),
    ("\u{2653}", "pisces"),
    ("\u{265F}\u{FE0F}", "black chess pawn"),
    ("\u{2692}\u{FE0F}", "hammer and pick"),
    ("\u{2693}", "anchor"),
    ("\u{2694}\u{FE0F}", "crossed swords"),
    ("\u{2696}\u{FE0F}", "scales"),
    ("\u{2697}\u{FE0F}", "alembic"),
    ("\u{2699}\u{FE0F}", "gear"),
    ("\u{269B}\u{FE0F}", "atom symbol"),
    ("\u{26A1}", "high voltage sign"),
    ("\u{26AA}", "medium white circle"),
    ("\u{26AB}", "medium black circle"),
    ("\u{26B0}\u{FE0F}", "coffin"),
    ("\u{26B1}\u{FE0F}", "funeral urn"),
    ("\u{26BD}", "soccer ball"),
    ("\u{26BE}", "baseball"),
    ("\u{26C4}", "snowman without snow"),
    ("\u{26C5}", "sun behind cloud"),
    ("\u{26C8}\u{FE0F}", "thunder cloud and rain"),
    ("\u{26CE}", "ophiuchus"),
    ("\u{26CF}\u{FE0F}", "pick"),
    ("\u{26D3}\u{FE0F}", "chains"),
    ("\u{26E9}\u{FE0F}", "shinto shrine"),
    ("\u{26EA}", "church"),
    ("\u{26F0}\u{FE0F}", "mountain"),
    ("\u{26F1}\u{FE0F}", "umbrella on ground"),
    ("\u{26F2}", "fountain"),
    ("\u{26F3}", "flag in hole"),
    ("\u{26F4}\u{FE0F}", "ferry"),
    ("\u{26F5}", "sailboat"),
    ("\u{26F7}\u{FE0F}", "skier"),
    ("\u{26F8}\u{FE0F}", "ice skate"),
    ("\u{26F9}\u{FE0F}", "person with ball"),
    ("\u{26FA}", "tent"),
    ("\u{26FD}", "fuel pump"),
    ("\u{2702}\u{FE0F}", "black scissors"),
    ("\u{2705}", "white heavy check mark"),
    ("\u{2708}\u{FE0F}", "airplane"),
    ("\u{2709}\u{FE0F}", "envelope"),
    ("\u{270A}", "raised fist"),
    ("\u{270B}", "raised hand"),
    ("\u{270C}\u{FE0F}", "victory hand"),
    ("\u{270D}\u{FE0F}", "writing hand"),
    ("\u{270F}\u{FE0F}", "pencil"),
    ("\u{2712}\u{FE0F}", "black nib"),
    ("\u{2714}\u{FE0F}", "heavy check mark"),
    ("\u{2716}\u{FE0F}", "heavy multiplication x"),
    ("\u{271D}\u{FE0F}", "latin cross"),
    ("\u{2721}\u{FE0F}", "star of david"),
    ("\u{2728}", "sparkles"),
    ("\u{2733}\u{FE0F}", "eight spoked asterisk"),
    ("\u{2734}\u{FE0F}", "eight pointed black star"),
    ("\u{2744}\u{FE0F}", "snowflake"),
    ("\u{2747}\u{FE0F}", "sparkle"),
    ("\u{274C}", "cross mark"),
    ("\u{274E}", "negative squared cross mark"),
    ("\u{2753}", "black question mark ornament"),
    ("\u{2754}", "white question mark ornament"),
    ("\u{2755}", "white exclamation mark ornament"),
    ("\u{2757}", "heavy exclamation mark symbol"),
    ("\u{2763}\u{FE0F}", "heavy heart exclamation mark ornament"),
    ("\u{2764}\u{FE0F}", "heavy black heart"),
    ("\u{2795}", "heavy plus sign"),
    ("\u{2796}", "heavy minus sign"),
    ("\u{2797}", "heavy division sign"),
    ("\u{27A1}\u{FE0F}", "black rightwards arrow"),
    ("\u{27B0}", "curly loop"),
    ("\u{27BF}", "double curly loop"),
    (
        "\u{2934}\u{FE0F}",
        "arrow pointing rightwards then curving upwards",
    ),
    (
        "\u{2935}\u{FE0F}",
        "arrow pointing rightwards then curving downwards",
    ),
    ("\u{2B05}\u{FE0F}", "leftwards black arrow"),
    ("\u{2B06}\u{FE0F}", "upwards black arrow"),
    ("\u{2B07}\u{FE0F}", "downwards black arrow"),
    ("\u{2B1B}", "black large square"),
    ("\u{2B1C}", "white large square"),
    ("\u{2B50}", "white medium star"),
    ("\u{2B55}", "heavy large circle"),
    ("\u{3030}\u{FE0F}", "wavy dash"),
    ("\u{3297}\u{FE0F}", "circled ideograph congratulation"),
    ("\u{3299}\u{FE0F}", "circled ideograph secret"),
    (
        "\u{1F17E}\u{FE0F}",
        "negative squared latin capital letter o",
    ),
    (
        "\u{1F17F}\u{FE0F}",
        "negative squared latin capital letter p",
    ),
    ("\u{1F194}", "squared id"),
    ("\u{1F195}", "squared new"),
    ("\u{1F196}", "squared ng"),
    ("\u{1F197}", "squared ok"),
    ("\u{1F198}", "squared sos"),
    ("\u{1F199}", "squared up with exclamation mark"),
    ("\u{1F19A}", "squared vs"),
    ("\u{1F201}", "squared katakana koko"),
    ("\u{1F202}\u{FE0F}", "squared katakana sa"),
    ("\u{1F21A}", "squared cjk unified ideograph-7121"),
    ("\u{1F22F}", "squared cjk unified ideograph-6307"),
    ("\u{1F232}", "squared cjk unified ideograph-7981"),
    ("\u{1F233}", "squared cjk unified ideograph-7a7a"),
    ("\u{1F234}", "squared cjk unified ideograph-5408"),
    ("\u{1F235}", "squared cjk unified ideograph-6e80"),
    ("\u{1F236}", "squared cjk unified ideograph-6709"),
    ("\u{1F237}\u{FE0F}", "squared cjk unified ideograph-6708"),
    ("\u{1F238}", "squared cjk unified ideograph-7533"),
    ("\u{1F239}", "squared cjk unified ideograph-5272"),
    ("\u{1F23A}", "squared cjk unified ideograph-55b6"),
    ("\u{1F250}", "circled ideograph advantage"),
    ("\u{1F251}", "circled ideograph accept"),
    ("\u{1F308}", "rainbow"),
    ("\u{1F30A}", "water wave"),
    ("\u{1F30B}", "volcano"),
    ("\u{1F30D}", "earth globe europe-africa"),
    ("\u{1F30E}", "earth globe americas"),
    ("\u{1F30F}", "earth globe asia-australia"),
    ("\u{1F311}", "new moon symbol"),
    ("\u{1F312}", "waxing crescent moon symbol"),
    ("\u{1F313}", "first quarter moon symbol"),
    ("\u{1F314}", "waxing gibbous moon symbol"),
    ("\u{1F315}", "full moon symbol"),
    ("\u{1F316}", "waning gibbous moon symbol"),
    ("\u{1F317}", "last quarter moon symbol"),
    ("\u{1F318}", "waning crescent moon symbol"),
    ("\u{1F319}", "crescent moon"),
    ("\u{1F31A}", "new moon with face"),
    ("\u{1F31B}", "first quarter moon with face"),
    ("\u{1F31C}", "last quarter moon with face"),
    ("\u{1F31D}", "full moon with face"),
    ("\u{1F31E}", "sun with face"),
    ("\u{1F31F}", "glowing star"),
    ("\u{1F321}\u{FE0F}", "thermometer"),
    ("\u{1F324}\u{FE0F}", "white sun with small cloud"),
    ("\u{1F326}\u{FE0F}", "white sun behind cloud with rain"),
    ("\u{1F327}\u{FE0F}", "cloud with rain"),
    ("\u{1F328}\u{FE0F}", "cloud with snow"),
    ("\u{1F329}\u{FE0F}", "cloud with lightning"),
    ("\u{1F32A}\u{FE0F}", "cloud with tornado"),
    ("\u{1F32B}\u{FE0F}", "fog"),
    ("\u{1F32C}\u{FE0F}", "wind blowing face"),
    ("\u{1F32D}", "hot dog"),
    ("\u{1F32E}", "taco"),
    ("\u{1F32F}", "burrito"),
    ("\u{1F330}", "chestnut"),
    ("\u{1F331}", "seedling"),
    ("\u{1F332}", "evergreen tree"),
    ("\u{1F333}", "deciduous tree"),
    ("\u{1F334}", "palm tree"),
    ("\u{1F335}", "cactus"),
    ("\u{1F336}\u{FE0F}", "hot pepper"),
    ("\u{1F337}", "tulip"),
    ("\u{1F338}", "cherry blossom"),
    ("\u{1F339}", "rose"),
    ("\u{1F33A}", "hibiscus"),
    ("\u{1F33B}", "sunflower"),
    ("\u{1F33C}", "blossom"),
    ("\u{1F33D}", "ear of maize"),
    ("\u{1F33E}", "ear of rice"),
    ("\u{1F33F}", "herb"),
    ("\u{1F340}", "four leaf clover"),
    ("\u{1F341}", "maple leaf"),
    ("\u{1F342}", "fallen leaf"),
    ("\u{1F343}", "leaf fluttering in wind"),
    ("\u{1F344}", "mushroom"),
    ("\u{1F345}", "tomato"),
    ("\u{1F346}", "aubergine"),
    ("\u{1F347}", "grapes"),
    ("\u{1F348}", "melon"),
    ("\u{1F349}", "watermelon"),
    ("\u{1F34A}", "tangerine"),
    ("\u{1F34B}", "lemon"),
    ("\u{1F34C}", "banana"),
    ("\u{1F34D}", "pineapple"),
    ("\u{1F34E}", "red apple"),
    ("\u{1F34F}", "green apple"),
    ("\u{1F350}", "pear"),
    ("\u{1F351}", "peach"),
    ("\u{1F352}", "cherries"),
    ("\u{1F353}", "strawberry"),
    ("\u{1F354}", "hamburger"),
    ("\u{1F355}", "slice of pizza"),
    ("\u{1F356}", "meat on bone"),
    ("\u{1F357}", "poultry leg"),
    ("\u{1F358}", "rice cracker"),
    ("\u{1F359}", "rice ball"),
    ("\u{1F35A}", "cooked rice"),
    ("\u{1F35B}", "curry and rice"),
    ("\u{1F35C}", "steaming bowl"),
    ("\u{1F35D}", "spaghetti"),
    ("\u{1F35E}", "bread"),
    ("\u{1F35F}", "french fries"),
    ("\u{1F360}", "roasted sweet potato"),
    ("\u{1F361}", "dango"),
    ("\u{1F362}", "oden"),
    ("\u{1F363}", "sushi"),
    ("\u{1F364}", "fried shrimp"),
    ("\u{1F365}", "fish cake with swirl design"),
    ("\u{1F366}", "soft ice cream"),
    ("\u{1F367}", "shaved ice"),
    ("\u{1F368}", "ice cream"),
    ("\u{1F369}", "doughnut"),
    ("\u{1F36A}", "cookie"),
    ("\u{1F36B}", "chocolate bar"),
    ("\u{1F36C}", "candy"),
    ("\u{1F36D}", "lollipop"),
    ("\u{1F36E}", "custard"),
    ("\u{1F36F}", "honey pot"),
    ("\u{1F370}", "shortcake"),
    ("\u{1F371}", "bento box"),
    ("\u{1F372}", "pot of food"),
    ("\u{1F373}", "cooking"),
    ("\u{1F374}", "fork and knife"),
    ("\u{1F375}", "teacup without handle"),
    ("\u{1F376}", "sake bottle and cup"),
    ("\u{1F377}", "wine glass"),
    ("\u{1F378}", "cocktail glass"),
    ("\u{1F379}", "tropical drink"),
    ("\u{1F37A}", "beer mug"),
    ("\u{1F37B}", "clinking beer mugs"),
    ("\u{1F37D}\u{FE0F}", "fork and knife with plate"),
    ("\u{1F37E}", "bottle with popping cork"),
    ("\u{1F37F}", "popcorn"),
    ("\u{1F382}", "birthday cake"),
    ("\u{1F383}", "jack-o-lantern"),
    ("\u{1F384}", "christmas tree"),
    ("\u{1F38B}", "tanabata tree"),
    ("\u{1F38C}", "crossed flags"),
    ("\u{1F38D}", "pine decoration"),
    ("\u{1F38E}", "japanese dolls"),
    ("\u{1F390}", "wind chime"),
    ("\u{1F396}\u{FE0F}", "military medal"),
    ("\u{1F397}\u{FE0F}", "reminder ribbon"),
    ("\u{1F399}\u{FE0F}", "studio microphone"),
    ("\u{1F39A}\u{FE0F}", "level slider"),
    ("\u{1F39B}\u{FE0F}", "control knobs"),
    ("\u{1F39E}\u{FE0F}", "film frames"),
    ("\u{1F39F}\u{FE0F}", "admission tickets"),
    ("\u{1F3A0}", "carousel horse"),
    ("\u{1F3A1}", "ferris wheel"),
    ("\u{1F3A2}", "roller coaster"),
    ("\u{1F3A3}", "fishing pole and fish"),
    ("\u{1F3A4}", "microphone"),
    ("\u{1F3A5}", "movie camera"),
    ("\u{1F3A7}", "headphone"),
    ("\u{1F3A8}", "artist palette"),
    ("\u{1F3AA}", "circus tent"),
    ("\u{1F3AB}", "ticket"),
    ("\u{1F3AC}", "clapper board"),
    ("\u{1F3AD}", "performing arts"),
    ("\u{1F3AE}", "video game"),
    ("\u{1F3AF}", "direct hit"),
    ("\u{1F3B0}", "slot machine"),
    ("\u{1F3B1}", "billiards"),
    ("\u{1F3B2}", "game die"),
    ("\u{1F3B3}", "bowling"),
    ("\u{1F3B7}", "saxophone"),
    ("\u{1F3B8}", "guitar"),
    ("\u{1F3B9}", "musical keyboard"),
    ("\u{1F3BA}", "trumpet"),
    ("\u{1F3BB}", "violin"),
    ("\u{1F3BC}", "musical score"),
    ("\u{1F3BD}", "running shirt with sash"),
    ("\u{1F3BE}", "tennis racquet and ball"),
    ("\u{1F3BF}", "ski and ski boot"),
    ("\u{1F3C0}", "basketball and hoop"),
    ("\u{1F3C1}", "chequered flag"),
    ("\u{1F3C2}", "snowboarder"),
    ("\u{1F3C3}", "runner"),
    ("\u{1F3C4}", "surfer"),
    ("\u{1F3C5}", "sports medal"),
    ("\u{1F3C6}", "trophy"),
    ("\u{1F3C7}", "horse racing"),
    ("\u{1F3C8}", "american football"),
    ("\u{1F3C9}", "rugby football"),
    ("\u{1F3CB}\u{FE0F}", "weight lifter"),
    ("\u{1F3CC}\u{FE0F}", "golfer"),
    ("\u{1F3CD}\u{FE0F}", "racing motorcycle"),
    ("\u{1F3CE}\u{FE0F}", "racing car"),
    ("\u{1F3CF}", "cricket bat and ball"),
    ("\u{1F3D0}", "volleyball"),
    ("\u{1F3D1}", "field hockey stick and ball"),
    ("\u{1F3D2}", "ice hockey stick and puck"),
    ("\u{1F3D3}", "table tennis paddle and ball"),
    ("\u{1F3D4}\u{FE0F}", "snow capped mountain"),
    ("\u{1F3D5}\u{FE0F}", "camping"),
    ("\u{1F3D6}\u{FE0F}", "beach with umbrella"),
    ("\u{1F3D7}\u{FE0F}", "building construction"),
    ("\u{1F3D8}\u{FE0F}", "house buildings"),
    ("\u{1F3DA}\u{FE0F}", "derelict house building"),
    ("\u{1F3DB}\u{FE0F}", "classical building"),
    ("\u{1F3DC}\u{FE0F}", "desert"),
    ("\u{1F3DD}\u{FE0F}", "desert island"),
    ("\u{1F3DF}\u{FE0F}", "stadium"),
    ("\u{1F3E0}", "house building"),
    ("\u{1F3E1}", "house with garden"),
    ("\u{1F3E2}", "office building"),
    ("\u{1F3E3}", "japanese post office"),
    ("\u{1F3E4}", "european post office"),
    ("\u{1F3E5}", "hospital"),
    ("\u{1F3E6}", "bank"),
    ("\u{1F3E8}", "hotel"),
    ("\u{1F3E9}", "love hotel"),
    ("\u{1F3EA}", "convenience store"),
    ("\u{1F3EB}", "school"),
    ("\u{1F3EC}", "department store"),
    ("\u{1F3ED}", "factory"),
    ("\u{1F3EE}", "izakaya lantern"),
    ("\u{1F3EF}", "japanese castle"),
    ("\u{1F3F0}", "european castle"),
    ("\u{1F3F3}\u{FE0F}", "waving white flag"),
    ("\u{1F3F4}", "waving black flag"),
    ("\u{1F3F5}\u{FE0F}", "rosette"),
    ("\u{1F3F7}\u{FE0F}", "label"),
    ("\u{1F3F8}", "badminton racquet and shuttlecock"),
    ("\u{1F3F9}", "bow and arrow"),
    ("\u{1F3FA}", "amphora"),
    ("\u{1F400}", "rat"),
    ("\u{1F401}", "mouse"),
    ("\u{1F402}", "ox"),
    ("\u{1F403}", "water buffalo"),
    ("\u{1F404}", "cow"),
    ("\u{1F405}", "tiger"),
    ("\u{1F406}", "leopard"),
    ("\u{1F407}", "rabbit"),
    ("\u{1F408}", "cat"),
    ("\u{1F40A}", "crocodile"),
    ("\u{1F40B}", "whale"),
    ("\u{1F40C}", "snail"),
    ("\u{1F40D}", "snake"),
    ("\u{1F40E}", "horse"),
    ("\u{1F40F}", "ram"),
    ("\u{1F410}", "goat"),
    ("\u{1F411}", "sheep"),
    ("\u{1F412}", "monkey"),
    ("\u{1F413}", "rooster"),
    ("\u{1F414}", "chicken"),
    ("\u{1F415}", "dog"),
    ("\u{1F416}", "pig"),
    ("\u{1F417}", "boar"),
    ("\u{1F418}", "elephant"),
    ("\u{1F419}", "octopus"),
    ("\u{1F41C}", "ant"),
    ("\u{1F41D}", "honeybee"),
    ("\u{1F41E}", "lady beetle"),
    ("\u{1F41F}", "fish"),
    ("\u{1F420}", "tropical fish"),
    ("\u{1F421}", "blowfish"),
    ("\u{1F422}", "turtle"),
    ("\u{1F424}", "baby chick"),
    ("\u{1F426}", "bird"),
    ("\u{1F427}", "penguin"),
    ("\u{1F428}", "koala"),
    ("\u{1F429}", "poodle"),
    ("\u{1F42A}", "dromedary camel"),
    ("\u{1F42B}", "bactrian camel"),
    ("\u{1F42C}", "dolphin"),
    ("\u{1F42D}", "mouse face"),
    ("\u{1F42E}", "cow face"),
    ("\u{1F42F}", "tiger face"),
    ("\u{1F430}", "rabbit face"),
    ("\u{1F431}", "cat face"),
    ("\u{1F433}", "spouting whale"),
    ("\u{1F434}", "horse face"),
    ("\u{1F435}", "monkey face"),
    ("\u{1F436}", "dog face"),
    ("\u{1F437}", "pig face"),
    ("\u{1F438}", "frog face"),
    ("\u{1F439}", "hamster face"),
    ("\u{1F43A}", "wolf face"),
    ("\u{1F43B}", "bear face"),
    ("\u{1F43C}", "panda face"),
    ("\u{1F43D}", "pig nose"),
    ("\u{1F43F}\u{FE0F}", "chipmunk"),
    ("\u{1F440}", "eyes"),
    ("\u{1F441}\u{FE0F}", "eye"),
    ("\u{1F442}", "ear"),
    ("\u{1F443}", "nose"),
    ("\u{1F444}", "mouth"),
    ("\u{1F445}", "tongue"),
    ("\u{1F446}", "white up pointing backhand index"),
    ("\u{1F447}", "white down pointing backhand index"),
    ("\u{1F448}", "white left pointing backhand index"),
    ("\u{1F449}", "white right pointing backhand index"),
    ("\u{1F44A}", "fisted hand sign"),
    ("\u{1F44B}", "waving hand sign"),
    ("\u{1F44C}", "ok hand sign"),
    ("\u{1F44D}", "thumbs up sign"),
    ("\u{1F44E}", "thumbs down sign"),
    ("\u{1F44F}", "clapping hands sign"),
    ("\u{1F450}", "open hands sign"),
    ("\u{1F466}", "boy"),
    ("\u{1F467}", "girl"),
    ("\u{1F468}", "man"),
    ("\u{1F469}", "woman"),
    ("\u{1F471}", "person with blond hair"),
    ("\u{1F474}", "older man"),
    ("\u{1F475}", "older woman"),
    ("\u{1F476}", "baby"),
    ("\u{1F47B}", "ghost"),
    ("\u{1F47D}", "extraterrestrial alien"),
    ("\u{1F480}", "skull"),
    ("\u{1F481}", "information desk person"),
    ("\u{1F483}", "dancer"),
    ("\u{1F485}", "nail polish"),
    ("\u{1F488}", "barber pole"),
    ("\u{1F489}", "syringe"),
    ("\u{1F48A}", "pill"),
    ("\u{1F48C}", "love letter"),
    ("\u{1F48E}", "gem stone"),
    ("\u{1F490}", "bouquet"),
    ("\u{1F492}", "wedding"),
    ("\u{1F493}", "beating heart"),
    ("\u{1F494}", "broken heart"),
    ("\u{1F495}", "two hearts"),
    ("\u{1F496}", "sparkling heart"),
    ("\u{1F497}", "growing heart"),
    ("\u{1F498}", "heart with arrow"),
    ("\u{1F499}", "blue heart"),
    ("\u{1F49A}", "green heart"),
    ("\u{1F49B}", "yellow heart"),
    ("\u{1F49C}", "purple heart"),
    ("\u{1F49D}", "heart with ribbon"),
    ("\u{1F49E}", "revolving hearts"),
    ("\u{1F49F}", "heart decoration"),
    ("\u{1F4A0}", "diamond shape with a dot inside"),
    ("\u{1F4A1}", "electric light bulb"),
    ("\u{1F4A3}", "bomb"),
    ("\u{1F4A5}", "collision symbol"),
    ("\u{1F4A6}", "splashing sweat symbol"),
    ("\u{1F4A7}", "droplet"),
    ("\u{1F4A8}", "dash symbol"),
    ("\u{1F4AA}", "flexed biceps"),
    ("\u{1F4AB}", "dizzy symbol"),
    ("\u{1F4B0}", "money bag"),
    ("\u{1F4B3}", "credit card"),
    ("\u{1F4B4}", "banknote with yen sign"),
    ("\u{1F4B5}", "banknote with dollar sign"),
    ("\u{1F4B6}", "banknote with euro sign"),
    ("\u{1F4B7}", "banknote with pound sign"),
    ("\u{1F4B8}", "money with wings"),
    ("\u{1F4BA}", "seat"),
    ("\u{1F4BB}", "personal computer"),
    ("\u{1F4BD}", "minidisc"),
    ("\u{1F4BE}", "floppy disk"),
    ("\u{1F4BF}", "optical disc"),
    ("\u{1F4C0}", "dvd"),
    ("\u{1F4C3}", "page with curl"),
    ("\u{1F4C4}", "page facing up"),
    ("\u{1F4C8}", "chart with upwards trend"),
    ("\u{1F4CA}", "bar chart"),
    ("\u{1F4CC}", "pushpin"),
    ("\u{1F4CD}", "round pushpin"),
    ("\u{1F4CE}", "paperclip"),
    ("\u{1F4CF}", "straight ruler"),
    ("\u{1F4D0}", "triangular ruler"),
    ("\u{1F4D1}", "bookmark tabs"),
    ("\u{1F4D2}", "ledger"),
    ("\u{1F4D3}", "notebook"),
    ("\u{1F4D4}", "notebook with decorative cover"),
    ("\u{1F4D5}", "closed book"),
    ("\u{1F4D6}", "open book"),
    ("\u{1F4D7}", "green book"),
    ("\u{1F4D8}", "blue book"),
    ("\u{1F4D9}", "orange book"),
    ("\u{1F4DA}", "books"),
    ("\u{1F4DC}", "scroll"),
    ("\u{1F4DD}", "memo"),
    ("\u{1F4DE}", "telephone receiver"),
    ("\u{1F4DF}", "pager"),
    ("\u{1F4E0}", "fax machine"),
    ("\u{1F4E1}", "satellite antenna"),
    ("\u{1F4E4}", "outbox tray"),
    ("\u{1F4E5}", "inbox tray"),
    ("\u{1F4E6}", "package"),
    ("\u{1F4E7}", "e-mail symbol"),
    ("\u{1F4E8}", "incoming envelope"),
    ("\u{1F4E9}", "envelope with downwards arrow above"),
    ("\u{1F4EA}", "closed mailbox with lowered flag"),
    ("\u{1F4EB}", "closed mailbox with raised flag"),
    ("\u{1F4EC}", "open mailbox with raised flag"),
    ("\u{1F4ED}", "open mailbox with lowered flag"),
    ("\u{1F4EE}", "postbox"),
    ("\u{1F4EF}", "postal horn"),
    ("\u{1F4F0}", "newspaper"),
    ("\u{1F4F1}", "mobile phone"),
    ("\u{1F4F2}", "mobile phone with rightwards arrow at left"),
    ("\u{1F4F5}", "no mobile phones"),
    ("\u{1F4F7}", "camera"),
    ("\u{1F4F8}", "camera with flash"),
    ("\u{1F4F9}", "video camera"),
    ("\u{1F4FA}", "television"),
    ("\u{1F4FB}", "radio"),
    ("\u{1F4FC}", "videocassette"),
    ("\u{1F4FD}\u{FE0F}", "film projector"),
    ("\u{1F4FF}", "prayer beads"),
    (
        "\u{1F503}",
        "clockwise downwards and upwards open circle arrows",
    ),
    (
        "\u{1F504}",
        "anticlockwise downwards and upwards open circle arrows",
    ),
    ("\u{1F50B}", "battery"),
    ("\u{1F50C}", "electric plug"),
    ("\u{1F50D}", "left-pointing magnifying glass"),
    ("\u{1F50E}", "right-pointing magnifying glass"),
    ("\u{1F50F}", "lock with ink pen"),
    ("\u{1F510}", "closed lock with key"),
    ("\u{1F512}", "lock"),
    ("\u{1F513}", "open lock"),
    ("\u{1F516}", "bookmark"),
    ("\u{1F517}", "link symbol"),
    ("\u{1F518}", "radio button"),
    ("\u{1F519}", "back with leftwards arrow above"),
    ("\u{1F51A}", "end with leftwards arrow above"),
    (
        "\u{1F51B}",
        "on with exclamation mark with left right arrow above",
    ),
    ("\u{1F51C}", "soon with rightwards arrow above"),
    ("\u{1F51D}", "top with upwards arrow above"),
    ("\u{1F51E}", "no one under eighteen symbol"),
    ("\u{1F520}", "input symbol for latin capital letters"),
    ("\u{1F521}", "input symbol for latin small letters"),
    ("\u{1F522}", "input symbol for numbers"),
    ("\u{1F523}", "input symbol for symbols"),
    ("\u{1F524}", "input symbol for latin letters"),
    ("\u{1F525}", "fire"),
    ("\u{1F526}", "electric torch"),
    ("\u{1F527}", "wrench"),
    ("\u{1F528}", "hammer"),
    ("\u{1F529}", "nut and bolt"),
    ("\u{1F52A}", "hocho"),
    ("\u{1F52B}", "pistol"),
    ("\u{1F52C}", "microscope"),
    ("\u{1F52D}", "telescope"),
    ("\u{1F52E}", "crystal ball"),
    ("\u{1F52F}", "six pointed star with middle dot"),
    ("\u{1F532}", "black square button"),
    ("\u{1F533}", "white square button"),
    ("\u{1F534}", "large red circle"),
    ("\u{1F535}", "large blue circle"),
    ("\u{1F536}", "large orange diamond"),
    ("\u{1F537}", "large blue diamond"),
    ("\u{1F538}", "small orange diamond"),
    ("\u{1F539}", "small blue diamond"),
    ("\u{1F53A}", "up-pointing red triangle"),
    ("\u{1F53B}", "down-pointing red triangle"),
    ("\u{1F549}\u{FE0F}", "om symbol"),
    ("\u{1F54B}", "kaaba"),
    ("\u{1F54C}", "mosque"),
    ("\u{1F54D}", "synagogue"),
    ("\u{1F54E}", "menorah with nine branches"),
    ("\u{1F56F}\u{FE0F}", "candle"),
    ("\u{1F570}\u{FE0F}", "mantelpiece clock"),
    ("\u{1F573}\u{FE0F}", "hole"),
    ("\u{1F574}\u{FE0F}", "man in business suit levitating"),
    ("\u{1F577}\u{FE0F}", "spider"),
    ("\u{1F579}\u{FE0F}", "joystick"),
    ("\u{1F57A}", "man dancing"),
    ("\u{1F587}\u{FE0F}", "linked paperclips"),
    ("\u{1F58A}\u{FE0F}", "lower left ballpoint pen"),
    ("\u{1F58B}\u{FE0F}", "lower left fountain pen"),
    ("\u{1F58C}\u{FE0F}", "lower left paintbrush"),
    ("\u{1F58D}\u{FE0F}", "lower left crayon"),
    ("\u{1F590}\u{FE0F}", "raised hand with fingers splayed"),
    ("\u{1F595}", "reversed hand with middle finger extended"),
    (
        "\u{1F596}",
        "raised hand with part between middle and ring fingers",
    ),
    ("\u{1F5A4}", "black heart"),
    ("\u{1F5A5}\u{FE0F}", "desktop computer"),
    ("\u{1F5A8}\u{FE0F}", "printer"),
    ("\u{1F5B1}\u{FE0F}", "three button mouse"),
    ("\u{1F5B2}\u{FE0F}", "trackball"),
    ("\u{1F5DC}\u{FE0F}", "compression"),
    ("\u{1F5DE}\u{FE0F}", "rolled-up newspaper"),
    ("\u{1F5E1}\u{FE0F}", "dagger knife"),
    ("\u{1F5FA}\u{FE0F}", "world map"),
    ("\u{1F5FB}", "mount fuji"),
    ("\u{1F5FC}", "tokyo tower"),
    ("\u{1F5FD}", "statue of liberty"),
    ("\u{1F5FF}", "moyai"),
    ("\u{1F600}", "grinning face"),
    ("\u{1F601}", "grinning face with smiling eyes"),
    ("\u{1F602}", "face with tears of joy"),
    ("\u{1F603}", "smiling face with open mouth"),
    ("\u{1F604}", "smiling face with open mouth and smiling eyes"),
    ("\u{1F605}", "smiling face with open mouth and cold sweat"),
    (
        "\u{1F606}",
        "smiling face with open mouth and tightly-closed eyes",
    ),
    ("\u{1F607}", "smiling face with halo"),
    ("\u{1F609}", "winking face"),
    ("\u{1F60A}", "smiling face with smiling eyes"),
    ("\u{1F60B}", "face savouring delicious food"),
    ("\u{1F60C}", "relieved face"),
    ("\u{1F60D}", "smiling face with heart-shaped eyes"),
    ("\u{1F60E}", "smiling face with sunglasses"),
    ("\u{1F60F}", "smirking face"),
    ("\u{1F610}", "neutral face"),
    ("\u{1F612}", "unamused face"),
    ("\u{1F613}", "face with cold sweat"),
    ("\u{1F614}", "pensive face"),
    ("\u{1F615}", "confused face"),
    ("\u{1F616}", "confounded face"),
    ("\u{1F617}", "kissing face"),
    ("\u{1F618}", "face throwing a kiss"),
    ("\u{1F619}", "kissing face with smiling eyes"),
    ("\u{1F61A}", "kissing face with closed eyes"),
    ("\u{1F61B}", "face with stuck-out tongue"),
    ("\u{1F61C}", "face with stuck-out tongue and winking eye"),
    (
        "\u{1F61D}",
        "face with stuck-out tongue and tightly-closed eyes",
    ),
    ("\u{1F61E}", "disappointed face"),
    ("\u{1F61F}", "worried face"),
    ("\u{1F620}", "angry face"),
    ("\u{1F621}", "pouting face"),
    ("\u{1F622}", "crying face"),
    ("\u{1F623}", "persevering face"),
    ("\u{1F624}", "face with look of triumph"),
    ("\u{1F625}", "disappointed but relieved face"),
    ("\u{1F626}", "frowning face with open mouth"),
    ("\u{1F627}", "anguished face"),
    ("\u{1F628}", "fearful face"),
    ("\u{1F629}", "weary face"),
    ("\u{1F62A}", "sleepy face"),
    ("\u{1F62B}", "tired face"),
    ("\u{1F62C}", "grimacing face"),
    ("\u{1F62D}", "loudly crying face"),
    ("\u{1F62E}", "face with open mouth"),
    ("\u{1F62F}", "hushed face"),
    ("\u{1F630}", "face with open mouth and cold sweat"),
    ("\u{1F631}", "face screaming in fear"),
    ("\u{1F632}", "astonished face"),
    ("\u{1F633}", "flushed face"),
    ("\u{1F634}", "sleeping face"),
    ("\u{1F635}", "dizzy face"),
    ("\u{1F637}", "face with medical mask"),
    ("\u{1F638}", "grinning cat face with smiling eyes"),
    ("\u{1F639}", "cat face with tears of joy"),
    ("\u{1F63A}", "smiling cat face with open mouth"),
    ("\u{1F63B}", "smiling cat face with heart-shaped eyes"),
    ("\u{1F63C}", "cat face with wry smile"),
    ("\u{1F63D}", "kissing cat face with closed eyes"),
    ("\u{1F63E}", "pouting cat face"),
    ("\u{1F63F}", "crying cat face"),
    ("\u{1F640}", "weary cat face"),
    ("\u{1F641}", "slightly frowning face"),
    ("\u{1F642}", "slightly smiling face"),
    ("\u{1F643}", "upside-down face"),
    ("\u{1F644}", "face with rolling eyes"),
    ("\u{1F645}", "face with no good gesture"),
    ("\u{1F646}", "face with ok gesture"),
    ("\u{1F647}", "person bowing deeply"),
    ("\u{1F648}", "see-no-evil monkey"),
    ("\u{1F649}", "hear-no-evil monkey"),
    ("\u{1F64A}", "speak-no-evil monkey"),
    ("\u{1F64B}", "happy person raising one hand"),
    ("\u{1F64C}", "person raising both hands in celebration"),
    ("\u{1F64D}", "person frowning"),
    ("\u{1F64E}", "person with pouting face"),
    ("\u{1F64F}", "person with folded hands"),
    ("\u{1F680}", "rocket"),
    ("\u{1F681}", "helicopter"),
    ("\u{1F682}", "steam locomotive"),
    ("\u{1F683}", "railway car"),
    ("\u{1F684}", "high-speed train"),
    ("\u{1F685}", "high-speed train with bullet nose"),
    ("\u{1F686}", "train"),
    ("\u{1F687}", "metro"),
    ("\u{1F688}", "light rail"),
    ("\u{1F689}", "station"),
    ("\u{1F68A}", "tram"),
    ("\u{1F68B}", "tram car"),
    ("\u{1F68C}", "bus"),
    ("\u{1F68D}", "oncoming bus"),
    ("\u{1F68E}", "trolleybus"),
    ("\u{1F68F}", "bus stop"),
    ("\u{1F691}", "ambulance"),
    ("\u{1F692}", "fire engine"),
    ("\u{1F693}", "police car"),
    ("\u{1F694}", "oncoming police car"),
    ("\u{1F695}", "taxi"),
    ("\u{1F696}", "oncoming taxi"),
    ("\u{1F697}", "automobile"),
    ("\u{1F698}", "oncoming automobile"),
    ("\u{1F699}", "recreational vehicle"),
    ("\u{1F69A}", "delivery truck"),
    ("\u{1F69B}", "articulated lorry"),
    ("\u{1F69C}", "tractor"),
    ("\u{1F69D}", "monorail"),
    ("\u{1F69E}", "mountain railway"),
    ("\u{1F69F}", "suspension railway"),
    ("\u{1F6A0}", "mountain cableway"),
    ("\u{1F6A1}", "aerial tramway"),
    ("\u{1F6A2}", "ship"),
    ("\u{1F6A4}", "speedboat"),
    ("\u{1F6A5}", "horizontal traffic light"),
    ("\u{1F6A6}", "vertical traffic light"),
    ("\u{1F6A7}", "construction sign"),
    ("\u{1F6A8}", "police cars revolving light"),
    ("\u{1F6A9}", "triangular flag on post"),
    ("\u{1F6AA}", "door"),
    ("\u{1F6AB}", "no entry sign"),
    ("\u{1F6AC}", "smoking symbol"),
    ("\u{1F6AD}", "no smoking symbol"),
    ("\u{1F6AF}", "do not litter symbol"),
    ("\u{1F6B0}", "potable water symbol"),
    ("\u{1F6B1}", "non-potable water symbol"),
    ("\u{1F6B2}", "bicycle"),
    ("\u{1F6B3}", "no bicycles"),
    ("\u{1F6B6}", "pedestrian"),
    ("\u{1F6B7}", "no pedestrians"),
    ("\u{1F6BD}", "toilet"),
    ("\u{1F6BF}", "shower"),
    ("\u{1F6C0}", "bath"),
    ("\u{1F6C1}", "bathtub"),
    ("\u{1F6CB}\u{FE0F}", "couch and lamp"),
    ("\u{1F6CF}\u{FE0F}", "bed"),
    ("\u{1F6D0}", "place of worship"),
    ("\u{1F6D5}", "hindu temple"),
    ("\u{1F6D7}", "elevator"),
    ("\u{1F6DC}", "wireless"),
    ("\u{1F6E0}\u{FE0F}", "hammer and wrench"),
    ("\u{1F6E1}\u{FE0F}", "shield"),
    ("\u{1F6E2}\u{FE0F}", "oil drum"),
    ("\u{1F6E5}\u{FE0F}", "motor boat"),
    ("\u{1F6E9}\u{FE0F}", "small airplane"),
    ("\u{1F6EB}", "airplane departure"),
    ("\u{1F6EC}", "airplane arriving"),
    ("\u{1F6F3}\u{FE0F}", "passenger ship"),
    ("\u{1F6F4}", "scooter"),
    ("\u{1F6F5}", "motor scooter"),
    ("\u{1F6F6}", "canoe"),
    ("\u{1F6F7}", "sled"),
    ("\u{1F6F8}", "flying saucer"),
    ("\u{1F6F9}", "skateboard"),
    ("\u{1F6FA}", "auto rickshaw"),
    ("\u{1F6FB}", "pickup truck"),
    ("\u{1F6FC}", "roller skate"),
    ("\u{1F7E0}", "large orange circle"),
    ("\u{1F7E1}", "large yellow circle"),
    ("\u{1F7E2}", "large green circle"),
    ("\u{1F7E3}", "large purple circle"),
    ("\u{1F7E4}", "large brown circle"),
    ("\u{1F7E5}", "large red square"),
    ("\u{1F7E6}", "large blue square"),
    ("\u{1F7E7}", "large orange square"),
    ("\u{1F7E8}", "large yellow square"),
    ("\u{1F7E9}", "large green square"),
    ("\u{1F7EA}", "large purple square"),
    ("\u{1F7EB}", "large brown square"),
    ("\u{1F7F0}", "heavy equals sign"),
    ("\u{1F90C}", "pinched fingers"),
    ("\u{1F90D}", "white heart"),
    ("\u{1F90E}", "brown heart"),
    ("\u{1F90F}", "pinching hand"),
    ("\u{1F910}", "zipper-mouth face"),
    ("\u{1F912}", "face with thermometer"),
    ("\u{1F914}", "thinking face"),
    ("\u{1F915}", "face with head-bandage"),
    ("\u{1F916}", "robot face"),
    ("\u{1F917}", "hugging face"),
    ("\u{1F918}", "sign of the horns"),
    ("\u{1F919}", "call me hand"),
    ("\u{1F91A}", "raised back of hand"),
    ("\u{1F91B}", "left-facing fist"),
    ("\u{1F91C}", "right-facing fist"),
    ("\u{1F91D}", "handshake"),
    ("\u{1F91E}", "hand with index and middle fingers crossed"),
    ("\u{1F91F}", "i love you hand sign"),
    ("\u{1F920}", "face with cowboy hat"),
    ("\u{1F921}", "clown face"),
    ("\u{1F922}", "nauseated face"),
    ("\u{1F923}", "rolling on the floor laughing"),
    ("\u{1F924}", "drooling face"),
    ("\u{1F926}", "face palm"),
    ("\u{1F927}", "sneezing face"),
    ("\u{1F928}", "face with one eyebrow raised"),
    ("\u{1F929}", "grinning face with star eyes"),
    (
        "\u{1F92A}",
        "grinning face with one large and one small eye",
    ),
    ("\u{1F92C}", "serious face with symbols covering mouth"),
    ("\u{1F92E}", "face with open mouth vomiting"),
    ("\u{1F92F}", "shocked face with exploding head"),
    ("\u{1F932}", "palms up together"),
    ("\u{1F933}", "selfie"),
    ("\u{1F937}", "shrug"),
    ("\u{1F938}", "person doing cartwheel"),
    ("\u{1F939}", "juggling"),
    ("\u{1F93A}", "fencer"),
    ("\u{1F93C}", "wrestlers"),
    ("\u{1F93F}", "diving mask"),
    ("\u{1F940}", "wilted flower"),
    ("\u{1F941}", "drum with drumsticks"),
    ("\u{1F942}", "clinking glasses"),
    ("\u{1F943}", "tumbler glass"),
    ("\u{1F944}", "spoon"),
    ("\u{1F945}", "goal net"),
    ("\u{1F947}", "first place medal"),
    ("\u{1F948}", "second place medal"),
    ("\u{1F949}", "third place medal"),
    ("\u{1F94A}", "boxing glove"),
    ("\u{1F94B}", "martial arts uniform"),
    ("\u{1F94C}", "curling stone"),
    ("\u{1F94D}", "lacrosse stick and ball"),
    ("\u{1F94E}", "softball"),
    ("\u{1F94F}", "flying disc"),
    ("\u{1F950}", "croissant"),
    ("\u{1F951}", "avocado"),
    ("\u{1F952}", "cucumber"),
    ("\u{1F953}", "bacon"),
    ("\u{1F954}", "potato"),
    ("\u{1F955}", "carrot"),
    ("\u{1F956}", "baguette bread"),
    ("\u{1F957}", "green salad"),
    ("\u{1F958}", "shallow pan of food"),
    ("\u{1F959}", "stuffed flatbread"),
    ("\u{1F95A}", "egg"),
    ("\u{1F95B}", "glass of milk"),
    ("\u{1F95C}", "peanuts"),
    ("\u{1F95D}", "kiwifruit"),
    ("\u{1F95E}", "pancakes"),
    ("\u{1F95F}", "dumpling"),
    ("\u{1F960}", "fortune cookie"),
    ("\u{1F961}", "takeout box"),
    ("\u{1F962}", "chopsticks"),
    ("\u{1F963}", "bowl with spoon"),
    ("\u{1F964}", "cup with straw"),
    ("\u{1F965}", "coconut"),
    ("\u{1F966}", "broccoli"),
    ("\u{1F967}", "pie"),
    ("\u{1F968}", "pretzel"),
    ("\u{1F969}", "cut of meat"),
    ("\u{1F96A}", "sandwich"),
    ("\u{1F96B}", "canned food"),
    ("\u{1F96C}", "leafy green"),
    ("\u{1F96D}", "mango"),
    ("\u{1F96E}", "moon cake"),
    ("\u{1F96F}", "bagel"),
    (
        "\u{1F970}",
        "smiling face with smiling eyes and three hearts",
    ),
    ("\u{1F971}", "yawning face"),
    ("\u{1F973}", "face with party horn and party hat"),
    ("\u{1F975}", "overheated face"),
    ("\u{1F976}", "freezing face"),
    ("\u{1F978}", "disguised face"),
    ("\u{1F980}", "crab"),
    ("\u{1F981}", "lion face"),
    ("\u{1F982}", "scorpion"),
    ("\u{1F983}", "turkey"),
    ("\u{1F984}", "unicorn face"),
    ("\u{1F985}", "eagle"),
    ("\u{1F986}", "duck"),
    ("\u{1F987}", "bat"),
    ("\u{1F988}", "shark"),
    ("\u{1F989}", "owl"),
    ("\u{1F98A}", "fox face"),
    ("\u{1F98B}", "butterfly"),
    ("\u{1F98C}", "deer"),
    ("\u{1F98D}", "gorilla"),
    ("\u{1F98E}", "lizard"),
    ("\u{1F98F}", "rhinoceros"),
    ("\u{1F990}", "shrimp"),
    ("\u{1F991}", "squid"),
    ("\u{1F992}", "giraffe face"),
    ("\u{1F993}", "zebra face"),
    ("\u{1F994}", "hedgehog"),
    ("\u{1F995}", "sauropod"),
    ("\u{1F996}", "t-rex"),
    ("\u{1F997}", "cricket"),
    ("\u{1F998}", "kangaroo"),
    ("\u{1F999}", "llama"),
    ("\u{1F99A}", "peacock"),
    ("\u{1F99B}", "hippopotamus"),
    ("\u{1F99C}", "parrot"),
    ("\u{1F99D}", "raccoon"),
    ("\u{1F99E}", "lobster"),
    ("\u{1F99F}", "mosquito"),
    ("\u{1F9A0}", "microbe"),
    ("\u{1F9A1}", "badger"),
    ("\u{1F9A2}", "swan"),
    ("\u{1F9A4}", "dodo"),
    ("\u{1F9A5}", "sloth"),
    ("\u{1F9A6}", "otter"),
    ("\u{1F9A7}", "orangutan"),
    ("\u{1F9A8}", "skunk"),
    ("\u{1F9AA}", "oyster"),
    ("\u{1F9AE}", "guide dog"),
    ("\u{1F9AF}", "probing cane"),
    ("\u{1F9B4}", "bone"),
    ("\u{1F9B5}", "leg"),
    ("\u{1F9B6}", "foot"),
    ("\u{1F9B7}", "tooth"),
    ("\u{1F9BB}", "ear with hearing aid"),
    ("\u{1F9BC}", "motorized wheelchair"),
    ("\u{1F9BD}", "manual wheelchair"),
    ("\u{1F9BE}", "mechanical arm"),
    ("\u{1F9BF}", "mechanical leg"),
    ("\u{1F9C0}", "cheese wedge"),
    ("\u{1F9C1}", "cupcake"),
    ("\u{1F9C2}", "salt shaker"),
    ("\u{1F9C3}", "beverage box"),
    ("\u{1F9C4}", "garlic"),
    ("\u{1F9C5}", "onion"),
    ("\u{1F9C6}", "falafel"),
    ("\u{1F9C7}", "waffle"),
    ("\u{1F9C8}", "butter"),
    ("\u{1F9C9}", "mate drink"),
    ("\u{1F9CA}", "ice cube"),
    ("\u{1F9CB}", "bubble tea"),
    ("\u{1F9CD}", "standing person"),
    ("\u{1F9CE}", "kneeling person"),
    ("\u{1F9CF}", "deaf person"),
    ("\u{1F9D1}", "adult"),
    (
        "\u{1F9D1}\u{200D}\u{2695}\u{FE0F}",
        "adult staff of aesculapius",
    ),
    ("\u{1F9D1}\u{200D}\u{2696}\u{FE0F}", "adult scales"),
    ("\u{1F9D1}\u{200D}\u{2708}\u{FE0F}", "adult airplane"),
    ("\u{1F9D1}\u{200D}\u{1F33E}", "adult ear of rice"),
    ("\u{1F9D1}\u{200D}\u{1F373}", "adult cooking"),
    ("\u{1F9D1}\u{200D}\u{1F393}", "adult graduation cap"),
    ("\u{1F9D1}\u{200D}\u{1F3A4}", "adult microphone"),
    ("\u{1F9D1}\u{200D}\u{1F3A8}", "adult artist palette"),
    ("\u{1F9D1}\u{200D}\u{1F3EB}", "adult school"),
    ("\u{1F9D1}\u{200D}\u{1F3ED}", "adult factory"),
    ("\u{1F9D1}\u{200D}\u{1F4BB}", "adult personal computer"),
    ("\u{1F9D1}\u{200D}\u{1F4BC}", "adult briefcase"),
    ("\u{1F9D1}\u{200D}\u{1F527}", "adult wrench"),
    ("\u{1F9D1}\u{200D}\u{1F52C}", "adult microscope"),
    ("\u{1F9D1}\u{200D}\u{1F680}", "adult rocket"),
    ("\u{1F9D1}\u{200D}\u{1F692}", "adult fire engine"),
    ("\u{1F9D2}", "child"),
    ("\u{1F9D3}", "older adult"),
    ("\u{1F9D4}", "bearded person"),
    ("\u{1F9D6}", "person in steamy room"),
    ("\u{1F9D7}", "person climbing"),
    ("\u{1F9D8}", "person in lotus position"),
    ("\u{1F9E0}", "brain"),
    ("\u{1F9E1}", "orange heart"),
    ("\u{1F9E7}", "red gift envelope"),
    ("\u{1F9E8}", "firecracker"),
    ("\u{1F9E9}", "jigsaw puzzle piece"),
    ("\u{1F9EA}", "test tube"),
    ("\u{1F9EB}", "petri dish"),
    ("\u{1F9EC}", "dna double helix"),
    ("\u{1F9ED}", "compass"),
    ("\u{1F9EE}", "abacus"),
    ("\u{1F9EF}", "fire extinguisher"),
    ("\u{1F9F0}", "toolbox"),
    ("\u{1F9F1}", "brick"),
    ("\u{1F9F2}", "magnet"),
    ("\u{1F9F7}", "safety pin"),
    ("\u{1F9F8}", "teddy bear"),
    ("\u{1F9F9}", "broom"),
    ("\u{1F9FA}", "basket"),
    ("\u{1F9FB}", "roll of paper"),
    ("\u{1F9FC}", "bar of soap"),
    ("\u{1F9FD}", "sponge"),
    ("\u{1F9FE}", "receipt"),
    ("\u{1F9FF}", "nazar amulet"),
    ("\u{1FA70}", "ballet shoes"),
    ("\u{1FA78}", "drop of blood"),
    ("\u{1FA79}", "adhesive bandage"),
    ("\u{1FA7A}", "stethoscope"),
    ("\u{1FA7B}", "x-ray"),
    ("\u{1FA7C}", "crutch"),
    ("\u{1FA80}", "yo-yo"),
    ("\u{1FA81}", "kite"),
    ("\u{1FA82}", "parachute"),
    ("\u{1FA83}", "boomerang"),
    ("\u{1FA85}", "pinata"),
    ("\u{1FA86}", "nesting dolls"),
    ("\u{1FA90}", "ringed planet"),
    ("\u{1FA91}", "chair"),
    ("\u{1FA92}", "razor"),
    ("\u{1FA93}", "axe"),
    ("\u{1FA94}", "diya lamp"),
    ("\u{1FA95}", "banjo"),
    ("\u{1FA97}", "accordion"),
    ("\u{1FA98}", "long drum"),
    ("\u{1FA99}", "coin"),
    ("\u{1FA9A}", "carpentry saw"),
    ("\u{1FA9B}", "screwdriver"),
    ("\u{1FA9C}", "ladder"),
    ("\u{1FA9D}", "hook"),
    ("\u{1FA9E}", "mirror"),
    ("\u{1FA9F}", "window"),
    ("\u{1FAA0}", "plunger"),
    ("\u{1FAA3}", "bucket"),
    ("\u{1FAA4}", "mouse trap"),
    ("\u{1FAA5}", "toothbrush"),
    ("\u{1FAA6}", "headstone"),
    ("\u{1FAA7}", "placard"),
    ("\u{1FAA9}", "mirror ball"),
    ("\u{1FAAB}", "low battery"),
    ("\u{1FAB2}", "beetle"),
    ("\u{1FAB3}", "cockroach"),
    ("\u{1FAB5}", "wood"),
    ("\u{1FAB6}", "feather"),
    ("\u{1FABF}", "goose"),
    ("\u{1FAC0}", "anatomical heart"),
    ("\u{1FAC1}", "lungs"),
    ("\u{1FAD0}", "blueberries"),
    ("\u{1FAD1}", "bell pepper"),
    ("\u{1FAD2}", "olive"),
    ("\u{1FAD3}", "flatbread"),
    ("\u{1FAD4}", "tamale"),
    ("\u{1FAD5}", "fondue"),
    ("\u{1FAD6}", "teapot"),
    ("\u{1FAD7}", "pouring liquid"),
    ("\u{1FAD8}", "beans"),
    ("\u{1FADA}", "ginger root"),
    ("\u{1FAE0}", "melting face"),
    ("\u{1FAE6}", "biting lip"),
    ("\u{1FAF0}", "hand with index finger and thumb crossed"),
    ("\u{1FAF6}", "heart hands"),
];

/// Byte length of the emoji cluster at the front of `s`, or `None` if `s`
/// does not start with one.
///
/// One emoji is often several codepoints (skin tone, variation selector,
/// keycap, ZWJ sequence, flag pair). Splitting per codepoint orphans the
/// modifiers, so keep the whole cluster together.
pub fn emoji_cluster_len(s: &str) -> Option<usize> {
    const ZWJ: char = '\u{200D}';
    const KEYCAP: char = '\u{20E3}';

    fn is_modifier(c: char) -> bool {
        matches!(c,
            // Fitzpatrick skin tones.
            '\u{1F3FB}'..='\u{1F3FF}'
            // Variation selectors: text vs emoji presentation.
            | '\u{FE0E}' | '\u{FE0F}'
            | KEYCAP
            // Tag characters, used by subdivision flags.
            | '\u{E0020}'..='\u{E007F}'
        )
    }

    fn is_regional(c: char) -> bool {
        matches!(c, '\u{1F1E6}'..='\u{1F1FF}')
    }

    /// Does this codepoint start an emoji?
    ///
    /// Ranges catch emoji newer than the dataset, else tofu via the text font.
    fn is_base(c: char) -> bool {
        if !name_of(&c.to_string()).is_empty() {
            return true;
        }
        matches!(c,
            '\u{1F300}'..='\u{1FAFF}'
            | '\u{1F000}'..='\u{1F02F}'
            | '\u{2600}'..='\u{27BF}'
            | '\u{2B00}'..='\u{2BFF}'
        )
    }

    let mut chars = s.char_indices();
    let (_, first) = chars.next()?;

    // Flags are exactly two regional indicators.
    if is_regional(first) {
        return match chars.next() {
            Some((i, second)) if is_regional(second) => Some(i + second.len_utf8()),
            _ => Some(first.len_utf8()),
        };
    }
    if !is_base(first) {
        return None;
    }

    let mut end = first.len_utf8();
    let rest = &s[end..];
    let mut it = rest.chars().peekable();
    while let Some(&c) = it.peek() {
        if is_modifier(c) {
            end += c.len_utf8();
            it.next();
            continue;
        }
        if c == ZWJ {
            // A ZWJ only joins when something follows it.
            let mut after = it.clone();
            after.next();
            match after.next() {
                Some(joined) if is_base(joined) || is_regional(joined) => {
                    end += c.len_utf8() + joined.len_utf8();
                    it.next();
                    it.next();
                    continue;
                }
                _ => break,
            }
        }
        break;
    }
    Some(end)
}

/// Unicode name for an emoji, or `""` if we have none.
pub fn name_of(emoji: &str) -> &'static str {
    match NAMES.binary_search_by(|(g, _)| (*g).cmp(emoji)) {
        Ok(i) => NAMES[i].1,
        Err(_) => "",
    }
}

/// Score `name` against `query`. Higher is better; `None` means no match.
///
/// Whole-word beats prefix beats substring beats subsequence.
fn score(name: &str, query: &str) -> Option<i32> {
    if name == query {
        return Some(1000);
    }
    if name.split_whitespace().any(|w| w == query) {
        return Some(800);
    }
    if name.split_whitespace().any(|w| w.starts_with(query)) {
        return Some(600);
    }
    if name.starts_with(query) {
        return Some(500);
    }
    if name.contains(query) {
        return Some(300);
    }
    // Loose subsequence fallback.
    let mut chars = name.chars();
    if query.chars().all(|q| chars.any(|c| c == q)) {
        // Shorter names win ties.
        return Some(100 - (name.len() as i32).min(90));
    }
    None
}
/// Flat search across all categories: `(category, emoji, supports_skin)`.
/// Matches on Unicode name and category, ranked best-first.
pub fn search(query: &str) -> Vec<(&'static str, &'static str, bool)> {
    let q = query.trim().to_lowercase();
    if q.is_empty() {
        let mut out = Vec::new();
        for cat in CATEGORIES {
            for (e, skin) in cat.emojis.iter() {
                out.push((cat.name, *e, *skin));
                if out.len() >= 200 {
                    return out;
                }
            }
        }
        return out;
    }
    let mut scored: Vec<(i32, &'static str, &'static str, bool)> = Vec::new();
    for cat in CATEGORIES {
        let cat_hit = cat.name.to_lowercase().contains(&q);
        for (e, skin) in cat.emojis.iter() {
            // Pasted emoji matches itself.
            let best = if *e == q {
                Some(1000)
            } else {
                score(name_of(e), &q).or(cat_hit.then_some(50))
            };
            if let Some(s) = best {
                scored.push((s, cat.name, *e, *skin));
            }
        }
    }
    scored.sort_by_key(|(s, ..)| std::cmp::Reverse(*s));
    scored.truncate(200);
    scored.into_iter().map(|(_, c, e, s)| (c, e, s)).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hands_and_people_accept_skin_tones() {
        // Tone picker needs these flags set.
        let waving = CATEGORIES
            .iter()
            .flat_map(|c| c.emojis.iter())
            .find(|(e, _)| *e == "\u{1F44B}")
            .expect("waving hand should be in the dataset");
        assert!(waving.1, "waving hand must accept a skin tone");

        let count = CATEGORIES
            .iter()
            .flat_map(|c| c.emojis.iter())
            .filter(|(_, skin)| *skin)
            .count();
        assert!(
            count > 20,
            "expected many skin-capable emoji, found {count}"
        );
    }

    #[test]
    fn every_category_has_a_tab_icon() {
        // Tabs use pictures; a missing icon is a blank button.
        for cat in CATEGORIES {
            assert!(!cat.icon.is_empty(), "{} has no tab icon", cat.name);
            // Icons render via the emoji font, not this name table.
            assert!(
                crate::emoji_font::EmojiFont::new().can_render(cat.icon),
                "{} tab icon {:?} cannot be rendered by the emoji font",
                cat.name,
                cat.icon
            );
        }
    }

    #[test]
    fn clusters_keep_skin_tones_with_their_base() {
        // Regression: toned clap split into base plus tofu box.
        let clap_dark = "\u{1F44F}\u{1F3FF}";
        assert_eq!(emoji_cluster_len(clap_dark), Some(clap_dark.len()));

        // Plain base.
        assert_eq!(emoji_cluster_len("\u{1F44F}"), Some("\u{1F44F}".len()));
        // Variation selector stays with the emoji before it.
        let skull = "\u{2620}\u{FE0F}";
        assert_eq!(emoji_cluster_len(skull), Some(skull.len()));
    }

    #[test]
    fn clusters_keep_zwj_sequences_whole() {
        // ZWJ family stays whole.
        let family = "\u{1F468}\u{200D}\u{1F469}\u{200D}\u{1F466}";
        assert_eq!(emoji_cluster_len(family), Some(family.len()));

        // Trailing ZWJ with nothing after it ends the cluster.
        let dangling = "\u{1F468}\u{200D}";
        assert_eq!(emoji_cluster_len(dangling), Some("\u{1F468}".len()));
    }

    #[test]
    fn clusters_take_flags_as_a_pair() {
        let flag = "\u{1F1EC}\u{1F1E7}";
        assert_eq!(emoji_cluster_len(flag), Some(flag.len()));
    }

    #[test]
    fn ordinary_text_is_not_an_emoji_cluster() {
        assert_eq!(emoji_cluster_len("hello"), None);
        assert_eq!(emoji_cluster_len(""), None);
        // Nerd Font icons are private-use, not emoji.
        assert_eq!(emoji_cluster_len("\u{F048A}"), None);
    }

    #[test]
    fn names_are_sorted_for_binary_search() {
        // Unsorted data mis-resolves silently instead of failing.
        assert!(
            NAMES.windows(2).all(|w| w[0].0 < w[1].0),
            "NAMES must be sorted and free of duplicates"
        );
    }

    #[test]
    fn lookup_resolves_unicode_names() {
        assert_eq!(name_of("\u{1F600}"), "grinning face");
        assert_eq!(name_of("not-an-emoji"), "");
    }

    #[test]
    fn search_matches_names_not_just_glyphs() {
        // Regression: glyph-only search never matched words like "smile".
        let hits = search("smile");
        assert!(!hits.is_empty(), "\"smile\" must find something");
        assert!(
            hits.iter().all(|(_, e, _)| !name_of(e).is_empty()),
            "every hit should be a named emoji"
        );
        assert!(
            name_of(hits[0].1).contains("smil"),
            "best hit should actually be a smiling face, got {:?}",
            name_of(hits[0].1)
        );
    }

    #[test]
    fn search_ranks_whole_words_above_scattered_letters() {
        let hits = search("cat");
        let top = name_of(hits[0].1);
        assert!(
            top.split_whitespace().any(|w| w.starts_with("cat")),
            "expected a cat, got {top:?}"
        );
    }

    #[test]
    fn search_still_finds_a_pasted_emoji() {
        let hits = search("\u{1F600}");
        assert_eq!(hits[0].1, "\u{1F600}");
    }

    #[test]
    fn categories_nonempty_and_search_works() {
        assert!(CATEGORIES.len() >= 8);
        let total: usize = CATEGORIES.iter().map(|c| c.emojis.len()).sum();
        assert!(total > 500, "expected exhaustive list, got {total}");
        assert!(!search("").is_empty());
    }

    #[test]
    fn skin_flags_present() {
        assert!(PEOPLE.iter().any(|(_, s)| *s));
        assert!(SMILEYS.iter().all(|(_, s)| !s));
    }
}
